CC = gcc -Wall -g
TARGET = aaa
OBJS = main.o add.o
CFLAGS = -c

$(TARGET) : $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

main.o : main.c add.h
	$(CC) $(CFLAGS) main.c -I.

add.o : add.c add.h
	$(CC) $(CFLAGS) add.c -I.

